### PR TITLE
Vignette review (2)

### PR DESCRIPTION
**Pull request by KetsiaGuichard**
Taking into account the feedback from the review of the vignette

Could you please provide your feedback by commenting on this PR ?

### CODE REVIEW

**Comment by loiclemarrec** [comment]
Or directly read this page : vignette("data-details").
=> the link is not effective

**Comment by loiclemarrec** [comment]
30km2
=> 30km^2

**Comment by loiclemarrec** [comment]
After asking for
set_telraam_token(token = 'YourTelraamAPIToken')
I put
> get_telraam_token()
Error in get_telraam_token() : 
  could not find function "get_telraam_token"
Is there any trouble ?

**Comment by loiclemarrec** [comment]
if data folder is not created you obtain this
"
> write_update_data(segment_name = "segment-burel", 
+                 start_date = as.Date('2023-09-01'), 
+                 end_date = as.Date('2023-09-30'))
Date in ISO8601 format; converting timezone from UTC to "Europe/Paris".
Error in gzfile(file, "wb") : cannot open the connection
In addition: Warning messages:
1:  29 failed to parse. 
2: In gzfile(file, "wb") :
  cannot open compressed file 'data/segment-burel.RData', probable reason 'No such file or directory'
"
but if you have created the folder "data" by your own, it's look ok
"
> write_update_data(segment_name = "segment-vigne",
+                   start_date = as.Date('2023-09-01'),
+                   end_date = as.Date('2023-09-30'))
Date in ISO8601 format; converting timezone from UTC to "Europe/Paris".
Warning message:
 22 failed to parse.
"

Conclusion : it would be great to creat otomatically the folde "data" if this latter do not exist yet.

Best regards

**Comment by ioana-gavra** [comment]
When I try to use retrieve_sensor() I get :
Error in strsplit(raw_segments, " ") : non-character argument
In addition: Warning messages:
1: In yaml.load(readLines(con, warn = readLines.warn), error.label = error.label,  :
  NAs introduced by coercion: 9000005665 is out of integer range

**Comment by KetsiaGuichard** [comment]
A suggestion from @PascalIrz: present the traffic dataset in a more user-friendly format (e.g., DT, kable) and/or add a summary of the dataset columns.

**Pull request merged**
